### ISSUE TITLE
add-filter does not seem to work

### ISSUE THREAD

**Issue by zwieberl** [GNUAspell/aspell#521] opened 2017-03-03 08:59 UTC
Hi,
I am probably using it wrong, but I can not figure this out. I want to use multiple filters but am unable to get aspell to work the way I expect it.
If I issue
`aspell --dont-backup  -t --personal=pfile -c FILE`
TeX-related things like `includegraphic` are correctly ignored.
But if I do any of the following, it does not get ignored:
`aspell --dont-backup  -n --add-filter tex --personal=pfile -c FILE`
`aspell --dont-backup  --add-filter nroff --add-filter tex --personal=pfile -c FILE`
`aspell --dont-backup  -lset-filter nroff:tex --personal=pfile -c FILE`

I am using:
`@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.6.1)`
on centOS7

Thanks!

**Comment by kevina** [comment] 2019-07-06 05:26
Sorry for the very long delay.

Adding multiple filters works for me.  The text and nroff filter however may be interfering with each others operation as they are not really meant to both be active.

Can you please attach a test file that demonstrates the bug.

**Comment by zwieberl** [comment] 2019-07-07 14:43
Unfortunately, I can't provide you with any examples, as I no longer have access to them. Sorry.

**Comment by kevina** [comment] 2019-07-07 20:29
Okay.  I am going to close this as it works for me and the problem is most likely that the filters are not meant to be combined.

**Closed by kevina** 2019-07-07 20:29 UTC
Labels: worksforme
