### ISSUE TITLE
Some library files are missing.

### ISSUE THREAD

**Issue by Pavel-Sayekat** [GNUAspell/aspell#542] opened 2018-06-19 11:41 UTC
The library files in aspell/common directory errors.hpp and errors.cpp , string_pair_enumeration.hpp, key_info.hpp, type_id.hpp, word_list.hpp,  are completely missing and in aspell/lib directory, filter-c.cpp, word_list-c.cpp, mutable_container-c.cpp, error-c.cpp, document_checker-c.cpp, string_map-c.cpp, config-c.cpp, string_enumeration-c.cpp, can_have_error-c.cpp, string_list-c.cpp, speller-c.cpp, string_pair_enumeration-c.cpp,  libraries are missing and in aspell/interfaces/cc/ aspell.h library file is missing.

**Comment by kevina** [comment] 2019-05-05 19:07
This is not a bug, these files are generated in the "autogen" script and not checked into git.  They are included in release tarballs.

**Closed by kevina** 2019-05-05 19:07 UTC
